---
# tasks file for nginx
- name: NGINX | Install NGINX package from EPEL Repo
  yum:
    name: nginx
    state: latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - restart nginx
  tags:
    - nginx-package
    - package
- name: NGINX | Create NGINX config file from temlate
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
  tags:
    - nginx-configuration